version: '3.1'
services:
  app:
    container_name: app
    ports:
      - 1337:8080
    build: .
    depends_on: 
      - db
    environment:
      - POSTGRES_DATASOURCE_URL=jdbc:postgresql://db:5432/employee
  db:
    container_name: db
    image: postgres
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/docker/volumes/test-vol/_data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=employee
      - PGDATA=/var/lib/docker/volumes/test-vol/_data/pgdata
volumes:
  pgdata: