server:
  error:
    include-binding-errors: always
    include-exception: false
    include-message: always
    include-stacktrace: never
  port: 1337
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: h2
    url: jdbc:h2:mem:employee
    username: h2
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true