spring:
  datasource:
    url: jdbc:h2:mem:employee
    username: h2
    password: h2
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 1337